markdown: kramdown
# Site settings
titre:
  fr: "Guillaume Geoffroy - Page professionnelle"
  en: "Guillaume Geoffroy - Professional page"
baseurl: ""

color-green: "#017100"
color-red: "#800000"
color-grey: "#AAAAAA"

nb-msg: 5

exclude:
 - [node_modules]
 - CNAME
 - README.md
 - cvdata.ini

#gems:
#  - jekyll-redirect-from
