markdown: kramdown
# Site settings
title: Guillaume Geoffroy
baseurl: ""

color-green: "#017100"
color-red: "#800000"
color-grey: "#AAAAAA"

nb-msg: 5

exclude: [node_modules]

#gems:
#  - jekyll-redirect-from
